// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MushroomPocket.EntityFrameworkCore;

#nullable disable

namespace MushroomPocket.Migrations
{
    [DbContext(typeof(MushroomDatabase))]
    [Migration("20240523104739_AddItemsTable")]
    partial class AddItemsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.5");

            modelBuilder.Entity("Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CharacterID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Effect")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CharacterID");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("MushroomMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("NoToTransform")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TransformTo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MushroomMasters");
                });

            modelBuilder.Entity("MushroomPocket.Character", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CharacterType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<int>("EXP")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HP")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Skill")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Characters");

                    b.HasDiscriminator<string>("CharacterType").HasValue("Character");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("MushroomPocket.Daisy", b =>
                {
                    b.HasBaseType("MushroomPocket.Character");

                    b.HasDiscriminator().HasValue("Daisy");
                });

            modelBuilder.Entity("MushroomPocket.Luigi", b =>
                {
                    b.HasBaseType("MushroomPocket.Character");

                    b.HasDiscriminator().HasValue("Luigi");
                });

            modelBuilder.Entity("MushroomPocket.Mario", b =>
                {
                    b.HasBaseType("MushroomPocket.Character");

                    b.HasDiscriminator().HasValue("Mario");
                });

            modelBuilder.Entity("MushroomPocket.Peach", b =>
                {
                    b.HasBaseType("MushroomPocket.Character");

                    b.HasDiscriminator().HasValue("Peach");
                });

            modelBuilder.Entity("MushroomPocket.Waluigi", b =>
                {
                    b.HasBaseType("MushroomPocket.Character");

                    b.HasDiscriminator().HasValue("Waluigi");
                });

            modelBuilder.Entity("MushroomPocket.Wario", b =>
                {
                    b.HasBaseType("MushroomPocket.Character");

                    b.HasDiscriminator().HasValue("Wario");
                });

            modelBuilder.Entity("Item", b =>
                {
                    b.HasOne("MushroomPocket.Character", null)
                        .WithMany("Inventory")
                        .HasForeignKey("CharacterID");
                });

            modelBuilder.Entity("MushroomPocket.Character", b =>
                {
                    b.Navigation("Inventory");
                });
#pragma warning restore 612, 618
        }
    }
}
