// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MushroomPocket;

#nullable disable

namespace MushroomPocket.Migrations
{
    [DbContext(typeof(MushroomDatabase))]
    [Migration("20240516030908_MushroomDb")]
    partial class MushroomDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.5");
#pragma warning restore 612, 618
        }
    }
}
